import { Geist, Geist_Mono, Paytone_One } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const paytone = Paytone_One({
  variable: "--font-paytone",
  subsets: ["latin"],
  weight: "400"
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${paytone.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
